name: ci

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      
      - name: Set up Node
      - uses: actions/setup-node@v4
        with:
          nodeversion: '22'
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
